# Generated by Django 5.1.2 on 2025-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_faculty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
