# Generated by Django 5.1.2 on 2025-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_content_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='courses/cover_images'),
        ),
    ]
