# Generated by Django 5.1.2 on 2025-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_assignment_created_assignment_slug_assignment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
