# Generated by Django 5.1.2 on 2025-05-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_assignment_is_graded_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='task',
        ),
    ]
