# Generated by Django 5.1.2 on 2025-01-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
