# Generated by Django 5.1.2 on 2025-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_usertask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'New Enrollment'), ('task', 'New Task Assigned'), ('deadline', 'Deadline Reminder'), ('submission', 'New Submission'), ('Assignment', 'New Assignment'), ('progress', 'Progress Update'), ('message', 'Message'), ('grade', 'Grade Update'), ('system', 'System Notification')], max_length=20),
        ),
    ]
