# Generated by Django 5.1.2 on 2025-01-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='owner',
        ),
    ]
