# Generated by Django 5.1.2 on 2025-05-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='task',
        ),
    ]
