# Generated by Django 5.1.2 on 2025-02-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_teacher_course_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Topic',
            new_name='topic',
        ),
    ]
