# Generated by Django 5.1.2 on 2025-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_topic_content_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
