# Generated by Django 5.1.2 on 2025-05-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_task', to='pages.assignment'),
        ),
    ]
