# Generated by Django 5.1.2 on 2025-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_submission_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.AddField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
