# Generated by Django 5.1.2 on 2025-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_assignment_status_usertask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
