# Generated by Django 5.1.2 on 2025-04-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
