# Generated by Django 5.1.2 on 2025-05-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_grade_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_grade', to='pages.submission'),
        ),
    ]
