# Generated by Django 5.1.2 on 2025-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_task_submission_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
