# Generated by Django 5.1.2 on 2025-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_grade_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
