# Generated by Django 5.1.2 on 2025-05-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_rubric_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubric',
            old_name='grade',
            new_name='assignment',
        ),
    ]
