# Generated by Django 5.1.2 on 2025-05-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_rename_grade_rubric_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='pages.assignment'),
        ),
    ]
