# Generated by Django 5.1.2 on 2025-05-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_rubricscore_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='title',
        ),
    ]
