# Generated by Django 5.1.2 on 2025-05-15 19:30

import django.db.models.deletion
import pages.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_rubric_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['is_completed', 'task__due_date']},
        ),
        migrations.CreateModel(
            name='MCQAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the question text in full', verbose_name='Question Text')),
                ('explanation', models.TextField(blank=True, help_text='Explanation to be shown after answering', null=True, verbose_name='Explanation')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer', verbose_name='Points')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1, verbose_name='Difficulty Level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active for use', verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit for this question in seconds', null=True, verbose_name='Time Limit (seconds)')),
                ('order', pages.fields.OrderField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_assessments', to='pages.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_assessments', to='pages.topic')),
            ],
            options={
                'verbose_name': 'MCQ Assessment',
                'verbose_name_plural': 'MCQ Assessments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('order', pages.fields.OrderField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pages.mcqassessment')),
            ],
            options={
                'verbose_name': 'MCQ Option',
                'verbose_name_plural': 'MCQ Options',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='mcqassessment',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 1)), name='points_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='mcqoption',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='unique_option_order_per_assessment'),
        ),
    ]
