# Generated by Django 5.1.2 on 2025-05-16 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_mcqattempt_mcqresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCQAssessment',
            new_name='Assessment',
        ),
        migrations.RenameModel(
            old_name='MCQAttempt',
            new_name='AssessmentAttempt',
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['order'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
    ]
