# Generated by Django 5.1.2 on 2025-05-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_assessmentquestion_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mcqoption',
            name='unique_option_order_per_assessment',
        ),
        migrations.AddConstraint(
            model_name='mcqoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_option_order_per_question'),
        ),
    ]
