# Generated by Django 5.1.2 on 2025-05-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_assessment_course_alter_assessment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='pages.assessment'),
        ),
    ]
