# Generated by Django 5.1.2 on 2025-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_task_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('assessment', 'Assessment'), ('exam', 'Exam'), ('project', 'Project')], default='quiz', max_length=20),
        ),
    ]
