# Generated by Django 5.1.2 on 2025-05-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.assessmentquestion'),
        ),
    ]
