# Generated by Django 5.1.2 on 2025-05-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_mcqresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price_tier',
            field=models.CharField(choices=[('free', 'Free'), ('1000', '₦1,000'), ('3000', '₦3,000'), ('5000', '₦5,000'), ('10000', '₦10,000'), ('30000', '₦30,000'), ('50000', '₦50,000')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CourseObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='pages.course')),
            ],
            options={
                'verbose_name_plural': 'Course Objectives',
                'ordering': ['course'],
            },
        ),
    ]
