# Generated by Django 5.1.2 on 2025-05-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_course_audience_course_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_tier',
            field=models.CharField(choices=[('free', 'Free'), ('1000', '1,000'), ('3000', '3,000'), ('5000', '5,000'), ('10000', '10,000'), ('30000', '30,000'), ('50000', '50,000')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.CreateModel(
            name='CourseRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='pages.course')),
            ],
            options={
                'verbose_name_plural': 'Course Requirements',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='CourseTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_trailers')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='pages.course')),
            ],
            options={
                'verbose_name_plural': 'Course Trailers',
                'ordering': ['course'],
            },
        ),
    ]
