# Generated by Django 5.1.2 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Ttudent', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Ttudent', max_length=10),
        ),
    ]
