# Generated by Django 5.1.2 on 2025-03-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_remove_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
